# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: ROMEA
email:
description: >- # this means to ignore newlines until "baseurl:"
  Website of the research laboratory robotics and mobility for the agriculture and environments, INRAE France
  # twitter_username: username
github_username: Romea
repository: Romea/Romea.github.io
# minimal_mistakes_skin: dark
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
url: https://romea.github.io

# Outputting
permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-scholar

atom_feed:
  hide: true

author:
  name   : "Robotics for the environment and the agriculture"
  avatar : "/assets/images/logo.png"
  bio    : ""
  links:
    #    - label: "Website"
    #  icon: "fas fa-fw fa-link"
    #  url: "https://"
    # - label: "Twitter"
    #   icon: "fab fa-fw fa-twitter-square"
    #   url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Romea"
    # - label: "Instagram"
    #   icon: "fab fa-fw fa-instagram"
    #   url: "https://instagram.com/"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Romea"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: splash
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # research
  - scope:
      path: ""
      type: research
    values:
      layout: single
      author_profile: false
      share: false
  # projects
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      author_profile: false
      share: false
  # people
  - scope:
      path: ""
      type: people
    values:
      layout: single
      author_profile: false
      share: false
  # jobs
  - scope:
      path: ""
      type: jobs
    values:
      layout: single
      author_profile: false
      share: false

category_archive:
  type: grid
  path: /categories/

tag_archive:
  type: grid
  path: /tags/

collections:
  research:
    output: true
    permalink: /research/:path/
  projects:
    output: true
    permalink: /projects/:path/
  people:
    output: true
    permalink: /people/:path/
  jobs:
    output: true
    permalink: /jobs/:path/


# Plugin configuration : Scholar
scholar:
  bibliography_list_attributes:
    reversed: "reversed" # This reverses the numbering of publications in the sorted group.
  type_order: [article, inproceedings]
  sort_by: year
  order: reverse
  details_dir:    bibliography
  type_names: { periodical: Special Issues (editor) }
  bibliography_template: bib
  repository: ./pdf
  #bibtex_skip_fields: ["abstract", "month_numeric", "url", "doi"]
  bibtex_skip_fields: 
    - abstract
    - month_numeric
    - url
  bibtex_filters:
    - latex

